# Generated by Django 3.0.4 on 2020-04-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lsemailforsend',
            old_name='send_date',
            new_name='Send_date',
        ),
        migrations.AddField(
            model_name='lsemailforsend',
            name='email_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
