# Generated by Django 3.0.6 on 2020-05-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_lsemailforsend_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsemailforsend',
            name='email_for',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='lsemailforsend',
            name='email_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
