# Generated by Django 3.0.6 on 2022-01-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LsPaykun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=30, null=True)),
                ('merchantId', models.CharField(blank=True, max_length=30, null=True)),
                ('accessToken', models.CharField(blank=True, max_length=30, null=True)),
                ('LiveMood', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Ls Paykun',
            },
        ),
    ]
