# Generated by Django 3.0.6 on 2020-10-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LsPaykun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=30, null=True)),
                ('MID', models.CharField(blank=True, max_length=30, null=True)),
                ('marchint_key', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ls Paykun',
            },
        ),
    ]
