# Generated by Django 3.0.6 on 2020-10-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lspaykun',
            old_name='MID',
            new_name='accessToken',
        ),
        migrations.RenameField(
            model_name='lspaykun',
            old_name='marchint_key',
            new_name='merchantId',
        ),
        migrations.AddField(
            model_name='lspaykun',
            name='LiveMood',
            field=models.BooleanField(default=False),
        ),
    ]
