# Generated by Django 3.0.6 on 2022-01-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lspaykun',
            name='accessToken',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lspaykun',
            name='merchantId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
