# Generated by Django 3.0.4 on 2020-04-20 18:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_auto_20200420_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='LsUserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(blank=True, max_length=20, null=True)),
                ('State', models.CharField(blank=True, max_length=20, null=True)),
                ('City', models.CharField(blank=True, max_length=20, null=True)),
                ('Zip_Code', models.CharField(blank=True, max_length=20, null=True)),
                ('Address_1', models.TextField(blank=True, null=True)),
                ('Address_2', models.TextField(blank=True, null=True)),
                ('Lend_Mark', models.CharField(blank=True, max_length=30, null=True)),
                ('Last_Update', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsUserAddress_user', to='accounts.LsUser')),
            ],
            options={
                'verbose_name_plural': 'LS User Address',
            },
        ),
    ]
