# Generated by Django 3.0.4 on 2020-04-12 14:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20200412_0233'),
        ('products', '0009_lsproduct_ticket_booking_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='LsWishlistType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'LS Wishlist Type',
            },
        ),
        migrations.CreateModel(
            name='LsWishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Wishlist_mail_status', models.BooleanField(default=False)),
                ('Create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsWishlist_product', to='products.LsProduct')),
                ('Update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsWishlist_update_by', to='accounts.LsUser')),
                ('Winsh_For', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsWishlist_product', to='wishlist.LsWishlistType')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsWishlist_create_by', to='accounts.LsUser')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsWishlist_user', to='accounts.LsUser')),
            ],
            options={
                'verbose_name_plural': 'LS Wishlist',
            },
        ),
    ]
