# Generated by Django 3.0.4 on 2020-04-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lswishlisttype',
            name='Title_code',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
