# Generated by Django 3.0.4 on 2020-04-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_lswishlisttype_title_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lswishlist',
            old_name='Product_id',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='lswishlist',
            old_name='Product_Name',
            new_name='Product_no',
        ),
        migrations.AlterField(
            model_name='lswishlisttype',
            name='Title_code',
            field=models.IntegerField(default=0),
        ),
    ]
