# Generated by Django 3.0.6 on 2020-08-01 17:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0016_auto_20200727_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='LsRefrralCodeEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refrral_link', models.CharField(blank=True, max_length=120, null=True)),
                ('Email', models.CharField(blank=True, max_length=120, null=True)),
                ('Mail_Send_Status', models.BooleanField(default=False)),
                ('Account_Create_Status', models.BooleanField(default=False)),
                ('Create_Dates', models.DateTimeField(default=django.utils.timezone.now)),
                ('Account_Create_Dates', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.LsUser')),
            ],
            options={
                'verbose_name_plural': 'LS User',
            },
        ),
    ]
