# Generated by Django 3.0.6 on 2020-08-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lsrefrralcodeemails',
            options={'verbose_name_plural': 'LS Refrral Code Emails'},
        ),
    ]
