# Generated by Django 3.0.4 on 2020-05-04 17:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LsAddsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_keyword', models.CharField(max_length=120)),
                ('Category_Title', models.CharField(max_length=120)),
                ('Status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Ls Adds Category',
            },
        ),
        migrations.CreateModel(
            name='LsAdds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Pogition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_adds.LsAddsCategory')),
            ],
            options={
                'verbose_name_plural': 'Ls Adds',
            },
        ),
    ]
