# Generated by Django 3.0.4 on 2020-04-28 18:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_auto_20200420_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='LsQerues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complate_id', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('Answer', models.TextField(blank=True, null=True)),
                ('Open_status', models.BooleanField(default=False)),
                ('Crate_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsQerues_user', to='accounts.LsUser')),
            ],
            options={
                'verbose_name_plural': 'LS Qerues',
            },
        ),
    ]
