# Generated by Django 3.0.4 on 2020-04-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsqerues',
            name='Title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='lsqerues',
            name='Update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
