# Generated by Django 3.0.6 on 2020-09-27 12:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0021_lsuser_my_coines'),
    ]

    operations = [
        migrations.CreateModel(
            name='LsUserApplayInsale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coins', models.IntegerField(default=0)),
                ('Create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Winner_Status', models.BooleanField(default=False)),
                ('user_Info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsUserApplayInsale_user', to='accounts.LsUser')),
            ],
            options={
                'verbose_name_plural': 'LS User Applay In sale',
            },
        ),
    ]
