# Generated by Django 3.0.6 on 2020-09-27 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200927_1752'),
        ('manage_sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsuserapplayinsale',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sale_LsProduct', to='products.LsProduct'),
        ),
    ]
