# Generated by Django 3.0.6 on 2020-09-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_sale', '0002_lsuserapplayinsale_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LsSaleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sale_Title', models.CharField(max_length=30)),
                ('Tag_Line', models.CharField(max_length=30)),
                ('Start_date', models.DateTimeField()),
                ('End_date', models.DateTimeField()),
                ('Running_Status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'LS Sale Info',
            },
        ),
    ]
