# Generated by Django 3.0.6 on 2020-09-28 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_sale', '0003_lssaleinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsuserapplayinsale',
            name='Sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sale_LsSaleInfo', to='manage_sale.LsSaleInfo'),
        ),
    ]
