# Generated by Django 3.0.6 on 2020-09-29 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manage_sale', '0004_lsuserapplayinsale_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='lssaleinfo',
            name='Winner_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
