# Generated by Django 3.0.4 on 2020-04-07 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('Image', models.ImageField(upload_to='user_imsge/%Y/%m/%d')),
                ('DOB', models.DateField()),
                ('Contact_no', models.IntegerField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'LS User',
            },
        ),
        migrations.CreateModel(
            name='LsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_pogition', models.CharField(max_length=20)),
                ('Image', models.ImageField(upload_to='banners/%Y/%m/%d')),
                ('Text1', models.CharField(blank=True, max_length=50, null=True)),
                ('Text2', models.CharField(blank=True, max_length=50, null=True)),
                ('Create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsBanner_update_by', to='accounts.LsUser')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsBanner_create_by', to='accounts.LsUser')),
            ],
            options={
                'verbose_name_plural': 'LS Banner',
            },
        ),
    ]
