# Generated by Django 3.0.4 on 2020-04-11 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lsuser',
            name='DOB',
        ),
        migrations.AddField(
            model_name='lsuser',
            name='DOJ',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
