# Generated by Django 3.0.4 on 2020-04-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200412_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsuser',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
