# Generated by Django 3.0.4 on 2020-04-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_lsuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsuser',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='user_imsge/%Y/%m/%d'),
        ),
    ]
