# Generated by Django 3.0.4 on 2020-04-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200420_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsbanner',
            name='Image_2',
            field=models.ImageField(blank=True, null=True, upload_to='banners_2/%Y/%m/%d'),
        ),
    ]
