# Generated by Django 3.0.4 on 2020-04-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_lsbanner_image_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsbanner',
            name='Text2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
