# Generated by Django 3.0.4 on 2020-04-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200430_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsbanner',
            name='Text1',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lsbanner',
            name='Text2',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
