# Generated by Django 3.0.4 on 2020-05-04 00:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200430_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='LsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_name', models.CharField(blank=True, max_length=120, null=True)),
                ('Title', models.CharField(blank=True, max_length=120, null=True)),
                ('Logo', models.ImageField(upload_to='project_logo/%Y/%m/%d')),
                ('favicon_icon', models.ImageField(upload_to='project/favicon/%Y/%m/%d')),
                ('Domain', models.CharField(blank=True, max_length=120, null=True)),
                ('Wallet_commition', models.FloatField(default=0)),
                ('System_email', models.EmailField(max_length=120)),
                ('System_email_Password', models.CharField(blank=True, max_length=120, null=True)),
                ('Create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsSettings_update_by', to='accounts.LsUser')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsSettings_create_by', to='accounts.LsUser')),
            ],
            options={
                'verbose_name_plural': 'LS Settings',
            },
        ),
    ]
