# Generated by Django 3.0.4 on 2020-05-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_lssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='lssettings',
            name='Wallet_descount',
            field=models.FloatField(default=0),
        ),
    ]
