# Generated by Django 3.0.4 on 2020-05-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_lssettings_wallet_descount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lssettings',
            name='Wallet_commition',
            field=models.FloatField(default=0, help_text='Amount in Rs.'),
        ),
        migrations.AlterField(
            model_name='lssettings',
            name='Wallet_descount',
            field=models.FloatField(default=0, help_text='Amount in %'),
        ),
    ]
