# Generated by Django 3.0.6 on 2020-05-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200504_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsuser',
            name='Mail_status',
            field=models.BooleanField(default=False),
        ),
    ]
