# Generated by Django 3.0.6 on 2020-07-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_lsuser_mail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsuser',
            name='UserImage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
