# Generated by Django 3.0.6 on 2020-07-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_lsuser_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsuser',
            name='UserImage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
