# Generated by Django 3.0.6 on 2020-07-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200725_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsuser',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
