# Generated by Django 3.0.6 on 2020-07-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200725_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsuser',
            name='Point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lsuser',
            name='User_referral_code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='lsuser',
            name='my_refrral_code',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
