# Generated by Django 3.0.6 on 2020-08-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200727_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsuser',
            name='Term_and_con',
            field=models.BooleanField(default=False),
        ),
    ]
