# Generated by Django 3.0.6 on 2020-08-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_lsuser_term_and_con'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lsuser',
            old_name='Term_and_con',
            new_name='Term_and_condition',
        ),
    ]
