# Generated by Django 3.0.6 on 2020-09-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200814_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='lssettings',
            name='Coines_rate',
            field=models.IntegerField(default=1, verbose_name='Coines in one Rs.'),
        ),
    ]
