# Generated by Django 3.0.6 on 2020-09-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_lssettings_coines_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lssettings',
            name='Coines_rate',
            field=models.IntegerField(default=1, verbose_name='Coines in 1 Rs.'),
        ),
    ]
