# Generated by Django 3.0.6 on 2020-09-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200927_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsuser',
            name='my_coines',
            field=models.IntegerField(default=0),
        ),
    ]
