# Generated by Django 3.0.6 on 2021-11-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_lsuser_my_coines'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsbanner',
            name='Publish',
            field=models.BooleanField(default=True),
        ),
    ]
