# Generated by Django 3.0.4 on 2020-04-21 18:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0012_lsproduct_winner_ticket'),
        ('accounts', '0005_auto_20200420_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='LsBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Title', models.CharField(blank=True, max_length=50, null=True)),
                ('Blog_Contect', models.TextField(blank=True, null=True)),
                ('Blog_description', models.TextField(blank=True, null=True)),
                ('Blog_Publish', models.BooleanField(default=False)),
                ('Create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Publish_date', models.DateTimeField()),
                ('Coupon_Code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsBlog_LsCoupons', to='products.LsCoupons')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsBlog_LsProduct', to='products.LsProduct')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsBlog_user', to='accounts.LsUser')),
            ],
            options={
                'verbose_name_plural': 'LS Bog',
            },
        ),
    ]
