# Generated by Django 3.0.4 on 2020-04-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsblog',
            name='Publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
