# Generated by Django 3.0.4 on 2020-04-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200422_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsblog',
            name='Blog_Title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
