# Generated by Django 3.0.4 on 2020-04-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200422_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsblog',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
    ]
