# Generated by Django 3.0.6 on 2020-07-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_lsblog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsblog',
            name='Meta_Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lsblog',
            name='Meta_Keyword',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lsblog',
            name='Meta_Title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
