# Generated by Django 3.0.6 on 2020-07-26 10:19

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200726_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsblog',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, max_length=120, null=True, populate_from='Blog_Title', unique_with=('Create_date__month',)),
        ),
    ]
