# Generated by Django 3.0.4 on 2020-04-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banner_pogition', models.CharField(max_length=20)),
                ('Image', models.ImageField(upload_to='banner')),
                ('text_1', models.CharField(max_length=50)),
                ('text_2', models.CharField(max_length=50)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
    ]
