# Generated by Django 3.0.4 on 2020-05-05 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LsCMSPageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=120)),
                ('Title', models.CharField(max_length=120)),
                ('Page_Content', models.TextField()),
                ('Create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Ls CMS Page Content',
            },
        ),
    ]
