# Generated by Django 3.0.6 on 2022-02-08 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_lscmspagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='lsUserProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Your_name', models.CharField(max_length=120)),
                ('Email', models.CharField(max_length=120)),
                ('Contact_no', models.CharField(max_length=120)),
                ('Product_name', models.CharField(max_length=120)),
                ('Product_URL', models.CharField(max_length=200)),
                ('Status', models.BooleanField(default=False)),
                ('Create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'ls User Product',
            },
        ),
    ]
