# Generated by Django 3.0.4 on 2020-04-23 19:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_auto_20200420_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='LsUserWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wallet_id', models.CharField(blank=True, max_length=120)),
                ('Wallet_code', models.CharField(blank=True, max_length=120)),
                ('wallet_admont', models.FloatField(default=0)),
                ('Wallet_status', models.BooleanField(default=False)),
                ('Create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsUserWallet_user', to='accounts.LsUser')),
            ],
            options={
                'verbose_name_plural': 'LS User Wallet',
            },
        ),
    ]
