# Generated by Django 3.0.4 on 2020-04-23 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LsStatements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_Id', models.CharField(blank=True, max_length=120)),
                ('Source', models.CharField(blank=True, max_length=120)),
                ('Tra_Type', models.BooleanField(default=False)),
                ('Befouer_Transaction_amount', models.FloatField(default=0)),
                ('Amount', models.FloatField(default=0)),
                ('After_Transaction_amount', models.FloatField(default=0)),
                ('Status', models.BooleanField(default=False)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'LS Statements',
            },
        ),
    ]
