# Generated by Django 3.0.4 on 2020-04-23 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200420_0053'),
        ('wallet', '0002_lsstatements'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsstatements',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsStatements_user', to='accounts.LsUser'),
        ),
    ]
