# Generated by Django 3.0.4 on 2020-04-23 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_lsstatements_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsstatements',
            name='wallet_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsUserWallet_user', to='wallet.LsUserWallet'),
        ),
    ]
