# Generated by Django 3.0.4 on 2020-04-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_lsstatements_wallet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsstatements',
            name='Source_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
