# Generated by Django 3.0.4 on 2020-04-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_lsstatements_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsstatements',
            name='Status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
