# Generated by Django 3.0.6 on 2020-07-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_auto_20200427_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsuserwallet',
            name='Wallet_status',
            field=models.BooleanField(default=True),
        ),
    ]
