# Generated by Django 3.0.6 on 2020-07-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_auto_20200721_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsuserwallet',
            name='wallet_admont',
            field=models.FloatField(default=100),
        ),
    ]
