# Generated by Django 3.0.4 on 2020-04-18 15:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_lsorder_order_status'),
        ('accounts', '0004_auto_20200412_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='LsPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.IntegerField(default=0)),
                ('Currenct_Type', models.CharField(blank=True, max_length=30, null=True)),
                ('Payment_status', models.CharField(blank=True, max_length=30, null=True)),
                ('Payment_Method', models.CharField(blank=True, max_length=30, null=True)),
                ('TXNID', models.CharField(blank=True, max_length=30, null=True)),
                ('TXNDATE', models.CharField(blank=True, max_length=30, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsPayments_order', to='orders.LsOrder')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsPayments_user', to='accounts.LsUser')),
            ],
            options={
                'verbose_name_plural': 'LS Add To Card',
            },
        ),
    ]
