# Generated by Django 3.0.4 on 2020-04-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytm_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lspayments',
            options={'verbose_name_plural': 'Ls Payments'},
        ),
        migrations.AlterField(
            model_name='lspayments',
            name='payment_amount',
            field=models.FloatField(default=0),
        ),
    ]
