# Generated by Django 3.0.4 on 2020-04-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytm_payment', '0002_auto_20200418_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lspayments',
            name='user',
        ),
        migrations.AddField(
            model_name='lspayments',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
