# Generated by Django 3.0.6 on 2020-07-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytm_payment', '0003_auto_20200418_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='LsPaytm_credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=30, null=True)),
                ('MID', models.CharField(blank=True, max_length=30, null=True)),
                ('marchint_key', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'LsPaytm_credentials',
            },
        ),
    ]
