# Generated by Django 3.0.4 on 2020-04-13 18:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_lsproduct_winner_status'),
        ('accounts', '0004_auto_20200412_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='LsAddToCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticket_no', models.IntegerField()),
                ('Create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsAddToCard_user', to='products.LsProduct')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsAddToCard_user', to='accounts.LsUser')),
            ],
            options={
                'verbose_name_plural': 'LS Add To Card',
            },
        ),
    ]
