# Generated by Django 3.0.4 on 2020-04-16 18:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200416_0116'),
        ('accounts', '0004_auto_20200412_0233'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=120)),
                ('No_of_item', models.IntegerField(default=0)),
                ('payment', models.IntegerField(default=0)),
                ('descount', models.BooleanField(default=False)),
                ('descount_amount', models.IntegerField(default=0)),
                ('total_payment', models.IntegerField(default=0)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, max_length=30, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsOrdeer_user', to='accounts.LsUser')),
            ],
            options={
                'verbose_name_plural': 'Ls Order',
            },
        ),
        migrations.CreateModel(
            name='LsOrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticket_no', models.IntegerField()),
                ('Book_status', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsOrdeerItem_order', to='orders.LsOrder')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsOrderItems_LsProduct', to='products.LsProduct')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsOrdeerItem_user', to='accounts.LsUser')),
            ],
            options={
                'verbose_name_plural': 'Ls Order Items',
            },
        ),
    ]
