# Generated by Django 3.0.4 on 2020-04-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_lsorder_lsorderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsorder',
            name='payment',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lsorder',
            name='total_payment',
            field=models.FloatField(default=0),
        ),
    ]
