# Generated by Django 3.0.4 on 2020-04-16 19:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200412_0233'),
        ('products', '0011_auto_20200416_0116'),
        ('orders', '0003_auto_20200417_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='LsUseDescount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('coupon_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsUseDescount_LsCoupons', to='products.LsCoupons')),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsUseDescount_order', to='orders.LsOrder')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsUseDescount_user', to='accounts.LsUser')),
            ],
            options={
                'verbose_name_plural': 'Ls Use Descount',
            },
        ),
    ]
