# Generated by Django 3.0.4 on 2020-04-17 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_lsusedescount'),
    ]

    operations = [
        migrations.CreateModel(
            name='LsOrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status_type', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'LS Order Status',
            },
        ),
        migrations.AddField(
            model_name='lsorder',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
