# Generated by Django 3.0.4 on 2020-04-17 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200418_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsorder',
            name='order_status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.LsOrderStatus'),
        ),
    ]
