# Generated by Django 3.0.4 on 2020-04-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_lsorder_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsorderstatus',
            name='message',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
