# Generated by Django 3.0.4 on 2020-04-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_lsorderstatus_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsorderitems',
            name='Winner',
            field=models.BooleanField(default=False),
        ),
    ]
