# Generated by Django 3.0.4 on 2020-04-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_lsorderitems_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsorderitems',
            name='Winner_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
