# Generated by Django 3.0.4 on 2020-04-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_lsorderitems_winner_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsorder',
            name='payment_for',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
