# Generated by Django 3.0.6 on 2020-05-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_lsorder_payment_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsorder',
            name='Mail_send_status',
            field=models.BooleanField(default=False),
        ),
    ]
