# Generated by Django 3.0.6 on 2020-08-13 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_lsorder_mail_send_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsorderitems',
            name='Nite',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lsorderitems',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
