# Generated by Django 3.0.6 on 2020-08-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200813_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsorderitems',
            name='Nite',
            field=models.TextField(blank=True, null=True),
        ),
    ]
