# Generated by Django 3.0.6 on 2020-09-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200813_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsorder',
            name='coines',
            field=models.IntegerField(default=0),
        ),
    ]
