# Generated by Django 3.0.6 on 2021-12-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_lsorder_coines'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsorderitems',
            name='Product_cycle',
            field=models.IntegerField(default=0),
        ),
    ]
