# Generated by Django 3.0.6 on 2026-09-06 21:27

from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_lsorder_coines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsorder',
            name='order_status',
            field=models.ForeignKey(blank=True, default=orders.models.get_default_order_status, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.LsOrderStatus'),
        ),
    ]
