# Generated by Django 3.0.6 on 2026-09-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20260907_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsorder',
            name='TXNDATE',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lsorder',
            name='TXNID',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
