# Generated by Django 3.0.6 on 2021-12-14 19:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_lsbanner_publish'),
        ('products', '0023_auto_20211215_0039'),
        ('orders', '0015_lsorderitems_product_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='LsWinners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_cycle', models.IntegerField(default=0)),
                ('winner_ticket', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsWinners_order', to='orders.LsOrder')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsWinners_LsProduct', to='products.LsProduct')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsWinners_user', to='accounts.LsUser')),
            ],
            options={
                'verbose_name_plural': 'Ls Winners',
            },
        ),
    ]
