# Generated by Django 3.0.6 on 2021-12-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_lswinners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsorder',
            name='descount_amount',
            field=models.FloatField(default=0),
        ),
    ]
