# Generated by Django 3.0.4 on 2020-04-07 19:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LsCategoryes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=20)),
                ('Image', models.ImageField(upload_to='categoryes/%Y/%m/%d')),
                ('Status', models.BooleanField(default=False)),
                ('Create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsCategoryes_update_by', to='accounts.LsUser')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsCategoryes_create_by', to='accounts.LsUser')),
            ],
            options={
                'verbose_name_plural': 'LS Categoryes',
            },
        ),
        migrations.CreateModel(
            name='LsProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=50)),
                ('ReyalPrice', models.IntegerField()),
                ('description', models.TextField()),
                ('product_link', models.URLField()),
                ('No_of_ticket', models.IntegerField()),
                ('Price_pr_ticket', models.IntegerField()),
                ('Imaghe', models.ImageField(upload_to='product/%Y/%m/%d')),
                ('Status', models.BooleanField(default=False)),
                ('Publich_date', models.DateField()),
                ('Ticket_open_date', models.DateField()),
                ('Meta_Keyword', models.TextField()),
                ('Open_status', models.BooleanField(default=False)),
                ('Create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsProduct_create_by', to='products.LsCategoryes')),
                ('Update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsProduct_update_by', to='accounts.LsUser')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsProduct_create_by', to='accounts.LsUser')),
            ],
            options={
                'verbose_name_plural': 'LS Product_name',
            },
        ),
        migrations.CreateModel(
            name='lsProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='product_images/%Y/%m/%d')),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lsProductImage_create_by', to='products.LsProduct')),
            ],
            options={
                'verbose_name_plural': 'LS Product Image',
            },
        ),
    ]
