# Generated by Django 3.0.4 on 2020-04-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsproduct',
            name='Product_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
