# Generated by Django 3.0.4 on 2020-04-07 22:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0002_lsproduct_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LsCoupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coupon_code', models.CharField(blank=True, max_length=120)),
                ('Coupon_Title', models.CharField(blank=True, max_length=20)),
                ('No_of_use', models.IntegerField(default=0)),
                ('No_of_used', models.IntegerField(default=0)),
                ('descount_range', models.IntegerField()),
                ('Start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('Create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Coupon_for', models.ManyToManyField(related_name='LsCoupon_coupon_for', to='accounts.LsUser')),
                ('Update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsCoupon_update_by', to='accounts.LsUser')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsCoupon_create_by', to='accounts.LsUser')),
            ],
            options={
                'verbose_name_plural': 'LS Coupons',
            },
        ),
    ]
