# Generated by Django 3.0.4 on 2020-04-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0003_lscoupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lscoupons',
            name='Coupon_for',
            field=models.ManyToManyField(blank=True, null=True, related_name='LsCoupon_coupon_for', to='accounts.LsUser'),
        ),
    ]
