# Generated by Django 3.0.4 on 2020-04-08 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200408_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lsproduct',
            old_name='Imaghe',
            new_name='Image',
        ),
    ]
