# Generated by Django 3.0.4 on 2020-04-09 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200409_0311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lsproduct',
            options={'verbose_name_plural': 'LS Productes'},
        ),
    ]
