# Generated by Django 3.0.4 on 2020-04-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0006_auto_20200410_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lscoupons',
            name='Coupon_for',
            field=models.ManyToManyField(related_name='LsCoupon_coupon_for', to='accounts.LsUser'),
        ),
    ]
