# Generated by Django 3.0.4 on 2020-04-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200410_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsproduct',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
    ]
