# Generated by Django 3.0.4 on 2020-04-11 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_lsproduct_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsproduct',
            name='Ticket_booking_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
