# Generated by Django 3.0.4 on 2020-04-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_lsproduct_ticket_booking_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsproduct',
            name='winner_status',
            field=models.BooleanField(default=False),
        ),
    ]
