# Generated by Django 3.0.4 on 2020-04-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200412_0233'),
        ('products', '0010_lsproduct_winner_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lscoupons',
            name='Coupon_for',
            field=models.ManyToManyField(blank=True, related_name='LsCoupon_coupon_for', to='accounts.LsUser'),
        ),
    ]
