# Generated by Django 3.0.4 on 2020-04-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200416_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsproduct',
            name='winner_ticket',
            field=models.IntegerField(default=0),
        ),
    ]
