# Generated by Django 3.0.4 on 2020-05-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_lsproduct_winner_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='lscategoryes',
            name='Category_slug',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
