# Generated by Django 3.0.4 on 2020-05-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_lscategoryes_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsproduct',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
