# Generated by Django 3.0.4 on 2020-05-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200503_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsproduct',
            name='Meta_Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lsproduct',
            name='Meta_Keyword',
            field=models.TextField(blank=True, null=True),
        ),
    ]
