# Generated by Django 3.0.4 on 2020-05-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200504_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsproduct',
            name='Meta_Title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
