# Generated by Django 3.0.6 on 2020-06-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_lsproduct_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsproductimage',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
