# Generated by Django 3.0.6 on 2020-06-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_lsproductimage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsproductimage',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
