# Generated by Django 3.0.6 on 2020-06-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200628_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsproduct',
            name='Product_TagLine',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='lsproduct',
            name='Product_name',
            field=models.CharField(max_length=150),
        ),
    ]
