# Generated by Django 3.0.6 on 2020-09-11 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0019_auto_20200628_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsproduct',
            name='Update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsProduct_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lsproduct',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LsProduct_create_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
