# Generated by Django 3.0.6 on 2020-09-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200911_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsproduct',
            name='Product_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lsproduct',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
