# Generated by Django 3.0.6 on 2020-09-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20200923_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsproduct',
            name='Max_Coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lsproduct',
            name='SaleWinnerStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lsproduct',
            name='UseForSale',
            field=models.BooleanField(default=False),
        ),
    ]
