# Generated by Django 3.0.6 on 2021-12-14 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200927_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lsproduct',
            old_name='winner_ticket',
            new_name='Product_cycle',
        ),
        migrations.RemoveField(
            model_name='lsproduct',
            name='Open_status',
        ),
        migrations.RemoveField(
            model_name='lsproduct',
            name='SaleWinnerStatus',
        ),
        migrations.RemoveField(
            model_name='lsproduct',
            name='winner_status',
        ),
    ]
