# Generated by Django 3.0.6 on 2020-11-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200927_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsproduct',
            name='Copy_Product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lsproduct',
            name='Perrent_Product',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
