# Generated by Django 3.0.6 on 2021-12-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20211215_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsproduct',
            name='Price_pr_ticket',
            field=models.IntegerField(default=0),
        ),
    ]
